"""add payment provider fields

Revision ID: 04f2c33918c8
Revises: 46247edf6f7f
Create Date: 2026-08-15 00:35:46.567280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f2c33918c8'
down_revision: Union[str, Sequence[str], None] = '46247edf6f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('provider', sa.Enum('paddle', 'razorpay', name='payment_provider'), nullable=False),
    sa.Column('event_id', sa.String(length=191), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_event_provider_id')
    )
    # op.add_column doesn't auto-create dependent Postgres enum types the way
    # op.create_table does (payment_provider above got created implicitly as a
    # side effect of the payment_webhook_events table DDL) — billing_cycle has
    # no such table to piggyback on, so it needs an explicit CREATE TYPE first.
    postgresql.ENUM('monthly', 'annual', name='billing_cycle').create(op.get_bind(), checkfirst=True)
    op.add_column('platform_subscriptions', sa.Column('provider', sa.Enum('paddle', 'razorpay', name='payment_provider'), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('billing_cycle', sa.Enum('monthly', 'annual', name='billing_cycle'), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('processor_customer_id', sa.String(length=128), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('processor_subscription_id', sa.String(length=128), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('processor_price_id', sa.String(length=128), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('payment_method_label', sa.String(length=64), nullable=True))
    op.add_column('platform_subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('platform_subscriptions', sa.Column('grace_period_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_platform_subscriptions_processor_subscription_id'), 'platform_subscriptions', ['processor_subscription_id'], unique=False)
    op.add_column('users', sa.Column('country_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    op.drop_index(op.f('ix_platform_subscriptions_processor_subscription_id'), table_name='platform_subscriptions')
    op.drop_column('platform_subscriptions', 'grace_period_ends_at')
    op.drop_column('platform_subscriptions', 'cancel_at_period_end')
    op.drop_column('platform_subscriptions', 'payment_method_label')
    op.drop_column('platform_subscriptions', 'processor_price_id')
    op.drop_column('platform_subscriptions', 'processor_subscription_id')
    op.drop_column('platform_subscriptions', 'processor_customer_id')
    op.drop_column('platform_subscriptions', 'billing_cycle')
    postgresql.ENUM(name='billing_cycle').drop(op.get_bind(), checkfirst=True)
    op.drop_column('platform_subscriptions', 'currency')
    op.drop_column('platform_subscriptions', 'provider')
    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
