"""add calendar connections

Revision ID: 0ee2704c6aab
Revises: 3be501bd4e4f
Create Date: 2026-08-09 16:30:37.069925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee2704c6aab'
down_revision: Union[str, Sequence[str], None] = '3be501bd4e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'zoom', 'calendly', 'cal_com', name='calendar_provider'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'provider', name='uq_calendar_connections_coach_provider')
    )
    op.create_index(op.f('ix_calendar_connections_coach_id'), 'calendar_connections', ['coach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_connections_coach_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
