"""client invite_accepted_at and multi-coach identity

Revision ID: 0f3ebafde444
Revises: 5e6dde6e1ee3
Create Date: 2026-08-17 16:04:03.064818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3ebafde444'
down_revision: Union[str, Sequence[str], None] = '5e6dde6e1ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('invite_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('clients_user_id_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_unique_constraint('uq_clients_user_id_coach_id', 'clients', ['user_id', 'coach_id'])
    # ### end Alembic commands ###

    # Backfill: invite_accepted_at replaces the old "user.password_hash is not
    # None" proxy for "has this client joined" — without this, every existing
    # already-joined client would suddenly read as invite-pending. joined_at
    # is the best available historical stand-in (accept always happened at or
    # shortly after that point in the old flow).
    op.execute(
        """
        UPDATE clients c
        SET invite_accepted_at = c.joined_at
        FROM users u
        WHERE c.user_id = u.id
          AND u.password_hash IS NOT NULL
          AND c.invite_accepted_at IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clients_user_id_coach_id', 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.create_unique_constraint(op.f('clients_user_id_key'), 'clients', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('clients', 'invite_accepted_at')
    # ### end Alembic commands ###
