"""add coaching start and end dates to clients

Revision ID: 2b137257a275
Revises: 172b47b2e7bc
Create Date: 2026-09-04 22:33:35.834304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b137257a275'
down_revision: Union[str, Sequence[str], None] = '172b47b2e7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('coaching_start_date', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('coaching_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'coaching_end_date')
    op.drop_column('clients', 'coaching_start_date')
    # ### end Alembic commands ###
