"""add daily page views

Revision ID: 2c9c02f6d3fd
Revises: b2c3d4e5f6a7
Create Date: 2026-09-30 21:12:26.383230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c9c02f6d3fd'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_page_views',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'path', name='uq_daily_page_views_date_path')
    )
    op.create_index(op.f('ix_daily_page_views_date'), 'daily_page_views', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_page_views_date'), table_name='daily_page_views')
    op.drop_table('daily_page_views')
    # ### end Alembic commands ###
