"""add forms and form_submissions

Revision ID: 2e4c5f9d402c
Revises: f8c0eff93386
Create Date: 2026-08-05 16:10:06.304833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e4c5f9d402c'
down_revision: Union[str, Sequence[str], None] = 'f8c0eff93386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'slug', name='uq_forms_coach_slug')
    )
    op.create_index(op.f('ix_forms_coach_id'), 'forms', ['coach_id'], unique=False)
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=False)
    op.create_table('form_submissions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_coach_id'), 'form_submissions', ['coach_id'], unique=False)
    op.add_column(
        'leads',
        sa.Column('source', sa.String(length=32), nullable=False, server_default='manual'),
    )
    op.add_column('leads', sa.Column('form_submission_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leads', 'form_submissions', ['form_submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'form_submission_id')
    op.drop_column('leads', 'source')
    op.drop_index(op.f('ix_form_submissions_coach_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_coach_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
