"""your ai team foundation: agent actions, consent, voice settings

Revision ID: 357a6ed0ceee
Revises: f780a3337c1e
Create Date: 2026-10-02 15:55:07.368488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357a6ed0ceee'
down_revision: Union[str, Sequence[str], None] = 'f780a3337c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('draft_message', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_client_id'), 'agent_actions', ['client_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_coach_id'), 'agent_actions', ['coach_id'], unique=False)
    op.drop_index(op.f('ix_retention_nudges_client_id'), table_name='retention_nudges')
    op.drop_index(op.f('ix_retention_nudges_coach_id'), table_name='retention_nudges')
    op.drop_table('retention_nudges')
    op.add_column('clients', sa.Column('companion_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('languages', sa.String(length=255), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('sample_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('sign_off', sa.String(length=100), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('say_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('never_say_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('checkin_questions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('quiet_hours_start', sa.Time(), nullable=True))
    op.add_column('coach_ai_assistant_settings', sa.Column('quiet_hours_end', sa.Time(), nullable=True))
    op.add_column(
        'coach_ai_assistant_settings',
        sa.Column('agents_paused', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'coach_ai_assistant_settings',
        sa.Column('briefing_freedom', sa.String(length=16), nullable=False, server_default='run_alone'),
    )
    op.add_column(
        'coach_ai_assistant_settings',
        sa.Column('client_agent_freedom', sa.String(length=16), nullable=False, server_default='ask_first'),
    )
    op.add_column(
        'coach_ai_assistant_settings',
        sa.Column('companion_freedom', sa.String(length=16), nullable=False, server_default='ask_first'),
    )
    op.add_column(
        'coach_ai_assistant_settings',
        sa.Column('drift_sensitivity', sa.String(length=16), nullable=False, server_default='normal'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_ai_assistant_settings', 'drift_sensitivity')
    op.drop_column('coach_ai_assistant_settings', 'companion_freedom')
    op.drop_column('coach_ai_assistant_settings', 'client_agent_freedom')
    op.drop_column('coach_ai_assistant_settings', 'briefing_freedom')
    op.drop_column('coach_ai_assistant_settings', 'agents_paused')
    op.drop_column('coach_ai_assistant_settings', 'quiet_hours_end')
    op.drop_column('coach_ai_assistant_settings', 'quiet_hours_start')
    op.drop_column('coach_ai_assistant_settings', 'checkin_questions_json')
    op.drop_column('coach_ai_assistant_settings', 'never_say_phrases')
    op.drop_column('coach_ai_assistant_settings', 'say_phrases')
    op.drop_column('coach_ai_assistant_settings', 'sign_off')
    op.drop_column('coach_ai_assistant_settings', 'sample_messages')
    op.drop_column('coach_ai_assistant_settings', 'languages')
    op.drop_column('clients', 'companion_consent_at')
    op.create_table('retention_nudges',
    sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('draft_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('retention_nudges_client_id_fkey')),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('retention_nudges_coach_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('retention_nudges_pkey'))
    )
    op.create_index(op.f('ix_retention_nudges_coach_id'), 'retention_nudges', ['coach_id'], unique=False)
    op.create_index(op.f('ix_retention_nudges_client_id'), 'retention_nudges', ['client_id'], unique=False)
    op.drop_index(op.f('ix_agent_actions_coach_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_client_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    # ### end Alembic commands ###
