"""add converted_client_id to leads

Revision ID: 383bcb70695e
Revises: 87540a221439
Create Date: 2026-08-16 23:33:04.818475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383bcb70695e'
down_revision: Union[str, Sequence[str], None] = '87540a221439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('converted_client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'leads_converted_client_id_fkey', 'leads', 'clients', ['converted_client_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leads_converted_client_id_fkey', 'leads', type_='foreignkey')
    op.drop_column('leads', 'converted_client_id')
    # ### end Alembic commands ###
