"""add client billing currency and invoice currency

Revision ID: 4f53c964e03d
Revises: a2c1aed332c2
Create Date: 2026-08-20 01:47:14.536928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f53c964e03d'
down_revision: Union[str, Sequence[str], None] = 'a2c1aed332c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('billing_currency', sa.String(length=3), nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency')
    op.drop_column('clients', 'billing_currency')
    # ### end Alembic commands ###
