"""add pending import rows

Revision ID: 53e33f2a7eba
Revises: 2b137257a275
Create Date: 2026-09-04 22:54:42.531378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53e33f2a7eba'
down_revision: Union[str, Sequence[str], None] = '2b137257a275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_import_rows',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('mapping_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_field_columns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_import_rows_coach_id'), 'pending_import_rows', ['coach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_import_rows_coach_id'), table_name='pending_import_rows')
    op.drop_table('pending_import_rows')
    # ### end Alembic commands ###
