"""add coach automation settings

Revision ID: 5e6dde6e1ee3
Revises: 64cdfcc4e4da
Create Date: 2026-08-17 13:02:30.666308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6dde6e1ee3'
down_revision: Union[str, Sequence[str], None] = '64cdfcc4e4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_automation_settings',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('auto_onboarding_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_assign_template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['auto_assign_template_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('coach_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_automation_settings')
    # ### end Alembic commands ###
