"""add program templates and client niche

Revision ID: 64cdfcc4e4da
Revises: b204f46538a0
Create Date: 2026-08-17 12:08:22.536496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cdfcc4e4da'
down_revision: Union[str, Sequence[str], None] = 'b204f46538a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('niche', sa.String(length=64), nullable=True))
    op.add_column('program_items', sa.Column('week_number', sa.Integer(), nullable=True))
    op.add_column(
        'program_items',
        sa.Column('item_kind', sa.String(length=16), nullable=False, server_default='milestone'),
    )
    op.add_column('program_items', sa.Column('linked_form_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'program_items_linked_form_id_fkey', 'program_items', 'forms', ['linked_form_id'], ['id'],
        ondelete='SET NULL',
    )
    # NOT NULL with a server_default (not just the ORM's Python-side default=False)
    # since the programs table already has real rows — a plain NOT NULL add
    # would fail against existing data.
    op.add_column('programs', sa.Column('is_template', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('programs', sa.Column('client_selectable', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('programs', sa.Column('duration_weeks', sa.Integer(), nullable=True))
    op.add_column('programs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('programs', sa.Column('checkin_cadence', sa.String(length=64), nullable=True))
    op.add_column('programs', sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('programs', sa.Column('price_currency', sa.String(length=3), nullable=True))
    op.add_column('programs', sa.Column('billing_cadence', sa.String(length=16), nullable=True))
    op.add_column('programs', sa.Column('assigned_from_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'programs_assigned_from_template_id_fkey', 'programs', 'programs',
        ['assigned_from_template_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('programs_assigned_from_template_id_fkey', 'programs', type_='foreignkey')
    op.drop_column('programs', 'assigned_from_template_id')
    op.drop_column('programs', 'billing_cadence')
    op.drop_column('programs', 'price_currency')
    op.drop_column('programs', 'price_amount')
    op.drop_column('programs', 'checkin_cadence')
    op.drop_column('programs', 'description')
    op.drop_column('programs', 'duration_weeks')
    op.drop_column('programs', 'client_selectable')
    op.drop_column('programs', 'is_template')
    op.drop_constraint('program_items_linked_form_id_fkey', 'program_items', type_='foreignkey')
    op.drop_column('program_items', 'linked_form_id')
    op.drop_column('program_items', 'item_kind')
    op.drop_column('program_items', 'week_number')
    op.drop_column('clients', 'niche')
    # ### end Alembic commands ###
