"""add coach profile gallery images

Revision ID: 7055ef21211d
Revises: 71d34c1b59e0
Create Date: 2026-08-17 17:06:23.299261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7055ef21211d'
down_revision: Union[str, Sequence[str], None] = '71d34c1b59e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_profiles', sa.Column('gallery_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_profiles', 'gallery_image_urls')
    # ### end Alembic commands ###
