"""add program started_at

Revision ID: 71d34c1b59e0
Revises: 0f3ebafde444
Create Date: 2026-08-17 16:40:08.860128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d34c1b59e0'
down_revision: Union[str, Sequence[str], None] = '0f3ebafde444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('started_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'started_at')
    # ### end Alembic commands ###
