"""add featured_on_public_profile to forms

Revision ID: 76949cc64a08
Revises: 4f53c964e03d
Create Date: 2026-09-04 01:19:48.691592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76949cc64a08'
down_revision: Union[str, Sequence[str], None] = '4f53c964e03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'forms',
        sa.Column(
            'featured_on_public_profile',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'featured_on_public_profile')
    # ### end Alembic commands ###
