"""add custom fields

Revision ID: 808576ccb19a
Revises: 3ced6a3edd9a
Create Date: 2026-08-12 17:29:37.131465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '808576ccb19a'
down_revision: Union[str, Sequence[str], None] = '3ced6a3edd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_groups',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_groups_coach_id'), 'custom_field_groups', ['coach_id'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'number', 'currency', 'percentage', 'date', 'dropdown', 'multi_select', 'checkbox', 'rating', 'url', 'email', 'phone', name='custom_field_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['custom_field_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_definitions_coach_id'), 'custom_field_definitions', ['coach_id'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_group_id'), 'custom_field_definitions', ['group_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['definition_id'], ['custom_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'client_id', name='uq_custom_field_value_def_client')
    )
    op.create_index(op.f('ix_custom_field_values_client_id'), 'custom_field_values', ['client_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_definition_id'), 'custom_field_values', ['definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_field_values_definition_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_client_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_custom_field_definitions_group_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_coach_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_groups_coach_id'), table_name='custom_field_groups')
    op.drop_table('custom_field_groups')
    # ### end Alembic commands ###
