"""add subscription reminder tracking

Revision ID: 844101fe2943
Revises: 7055ef21211d
Create Date: 2026-08-17 17:14:19.230773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844101fe2943'
down_revision: Union[str, Sequence[str], None] = '7055ef21211d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_subscriptions', sa.Column('last_reminder_day_sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_subscriptions', 'last_reminder_day_sent')
    # ### end Alembic commands ###
