"""add paid_at to invoices

Revision ID: 98daef6dd1be
Revises: fca8bf554072
Create Date: 2026-08-17 11:39:09.041563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98daef6dd1be'
down_revision: Union[str, Sequence[str], None] = 'fca8bf554072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'paid_at')
    # ### end Alembic commands ###
