"""add bio and social links to coach_profiles

Revision ID: b204f46538a0
Revises: 98daef6dd1be
Create Date: 2026-08-17 11:50:58.645548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b204f46538a0'
down_revision: Union[str, Sequence[str], None] = '98daef6dd1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('coach_profiles', sa.Column('website_url', sa.String(length=1024), nullable=True))
    op.add_column('coach_profiles', sa.Column('instagram_url', sa.String(length=1024), nullable=True))
    op.add_column('coach_profiles', sa.Column('linkedin_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_profiles', 'linkedin_url')
    op.drop_column('coach_profiles', 'instagram_url')
    op.drop_column('coach_profiles', 'website_url')
    op.drop_column('coach_profiles', 'bio')
    # ### end Alembic commands ###
