"""add metrics and session notes

Revision ID: cf6d022b2487
Revises: 808576ccb19a
Create Date: 2026-08-12 19:49:39.395259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6d022b2487'
down_revision: Union[str, Sequence[str], None] = '808576ccb19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE ai_insight_type ADD VALUE IF NOT EXISTS 'client_snapshot'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_definitions_coach_id'), 'metric_definitions', ['coach_id'], unique=False)
    op.create_table('metric_entries',
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['definition_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_entries_client_id'), 'metric_entries', ['client_id'], unique=False)
    op.create_index(op.f('ix_metric_entries_definition_id'), 'metric_entries', ['definition_id'], unique=False)
    op.create_table('session_notes',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('discussion_notes', sa.Text(), nullable=True),
    sa.Column('key_insights', sa.Text(), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wins', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_notes_client_id'), 'session_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_session_notes_coach_id'), 'session_notes', ['coach_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no direct "remove enum value" op; leaving the added
    # 'client_snapshot' value in place on downgrade is the standard tradeoff.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_notes_coach_id'), table_name='session_notes')
    op.drop_index(op.f('ix_session_notes_client_id'), table_name='session_notes')
    op.drop_table('session_notes')
    op.drop_index(op.f('ix_metric_entries_definition_id'), table_name='metric_entries')
    op.drop_index(op.f('ix_metric_entries_client_id'), table_name='metric_entries')
    op.drop_table('metric_entries')
    op.drop_index(op.f('ix_metric_definitions_coach_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
