"""add message is_agent_sent flag

Revision ID: f4f78bff7d57
Revises: 357a6ed0ceee
Create Date: 2026-10-02 22:18:03.478474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4f78bff7d57'
down_revision: Union[str, Sequence[str], None] = '357a6ed0ceee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages',
        sa.Column('is_agent_sent', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_agent_sent')
    # ### end Alembic commands ###
