"""add retention nudges and automation email/retention settings

Revision ID: f780a3337c1e
Revises: 2c9c02f6d3fd
Create Date: 2026-10-02 15:27:50.264706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f780a3337c1e'
down_revision: Union[str, Sequence[str], None] = '2c9c02f6d3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_nudges',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('draft_message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_nudges_client_id'), 'retention_nudges', ['client_id'], unique=False)
    op.create_index(op.f('ix_retention_nudges_coach_id'), 'retention_nudges', ['coach_id'], unique=False)
    op.add_column(
        'coach_automation_settings',
        sa.Column('email_daily_briefing', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'coach_automation_settings',
        sa.Column('retention_agent_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_automation_settings', 'retention_agent_enabled')
    op.drop_column('coach_automation_settings', 'email_daily_briefing')
    op.drop_index(op.f('ix_retention_nudges_coach_id'), table_name='retention_nudges')
    op.drop_index(op.f('ix_retention_nudges_client_id'), table_name='retention_nudges')
    op.drop_table('retention_nudges')
    # ### end Alembic commands ###
