"""add subscription_valid_from to clients

Revision ID: fca8bf554072
Revises: 4098735da46a
Create Date: 2026-08-17 00:22:36.910074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca8bf554072'
down_revision: Union[str, Sequence[str], None] = '4098735da46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('subscription_valid_from', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'subscription_valid_from')
    # ### end Alembic commands ###
